# Generated by Django 4.0 on 2021-12-21 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateTimeField()),
                ('title_activity', models.CharField(max_length=255)),
                ('createddate_act', models.DateTimeField()),
                ('updateddate_act', models.DateTimeField()),
                ('status_activity', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('description', models.CharField(max_length=255)),
                ('createddate', models.DateTimeField()),
                ('updatedate', models.DateTimeField()),
                ('disableddate', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('createddate_survey', models.DateTimeField()),
                ('activity_id_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_data.activity')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_data.property'),
        ),
    ]
