# Generated by Django 4.0 on 2021-12-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='createddate_act',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updateddate_act',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='createddate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='updatedate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='createddate_survey',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
