# Generated by Django 4.0 on 2021-12-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_data', '0002_alter_activity_createddate_act_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='createddate_act',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='updateddate_act',
        ),
        migrations.RemoveField(
            model_name='property',
            name='createddate',
        ),
        migrations.RemoveField(
            model_name='property',
            name='updatedate',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='createddate_survey',
        ),
    ]
