# Generated by Django 4.0 on 2021-12-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_data', '0003_remove_activity_createddate_act_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status_activity',
            field=models.CharField(choices=[('Pendiente', 'P'), ('Finalizado', 'F'), ('Atrasado', 'A')], default=1, max_length=255),
        ),
    ]
